# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "scoreapi"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true

[default.package]
[default.package.parameters]

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
